---
title: "Music"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(knitr)
library(tidyverse)
library(kableExtra)
library(DT)
```

```{r}
top40all <- readRDS("input/top40.rds") %>% 
  mutate_if(is.numeric, as.integer) %>% 
  mutate_at("positie", as.integer) %>% 
  select(artiest, titel, positie, vorige, weken, jaar, week)
top40current <- tail(top40all, 40)
top40uniques <- top40all %>% 
  group_by(artiest, titel) %>% 
  mutate(binnenkomst = min(paste(jaar, week, sep = "-")),
         weekuit = max(paste(jaar, week, sep = "-")),
         weken = max(weken),
         hoogst = as.integer(min(positie))) %>% 
  ungroup %>% 
  distinct(artiest, titel, .keep_all = T) %>% 
  select(artiest, titel, weken, binnenkomst, weekuit, hoogst)

top2000all <- readRDS("input/top2000.rds") %>% 
  mutate_if(is.numeric, as.integer) %>% 
  select(artiest, titel, positie, jaar, release, hp)
top2000current <- head(top2000all, 2000)
top2000uniques <- top2000all %>% 
  group_by(artiest, titel) %>% 
  summarise(aantal = n(),
            hoogst = as.integer(min(positie)),
            laagst = as.integer(max(positie)),
            jarenintop2000 = paste(jaar, collapse = ",")) %>% 
  ungroup()

customdtfunc <- function(dataframe){
  datatable(dataframe, 
            options = list(
              pageLength = 40,
              lengthMenu = c(10,40,100)
            ),
            class = "cell-border",
            rownames = F,
            filter = "top",
            style = "bootstrap"
  )
}
```





Top 40
===

Top40 {.tabset}
---

### Top40 current

```{r}
customdtfunc(top40current)
```

### Top40 all

```{r}
customdtfunc(top40all)
```

### Top40 unique songs

```{r}
customdtfunc(top40uniques)
```

Top 2000
===

Top2000 {.tabset}
---

### Top2000 current

```{r}
customdtfunc(top2000current)
```

### Top2000 all

```{r}
customdtfunc(top2000all)
```

### Top2000 unique songs

```{r}
customdtfunc(top2000uniques)
```